// Bundled quotes per language — zero network, works fully offline.
const QUOTES = {
  en: [
    "Well begun is half done.",
    "The secret of getting ahead is getting started.",
    "Small steps every day.",
    "Do the hard thing first.",
    "You don't have to be great to start.",
    "Focus is saying no to a thousand good ideas.",
    "Discipline is choosing what you want most over what you want now.",
    "A calm mind brings inner strength.",
    "Simplicity is the ultimate sophistication.",
    "What you do today can improve all your tomorrows.",
    "Action is the antidote to anxiety.",
    "The best way out is always through.",
    "Slow is smooth, smooth is fast.",
    "One thing at a time, done well.",
    "Progress, not perfection.",
  ],
  ja: [
    "はじめが肝心。",
    "千里の道も一歩から。",
    "小さな一歩を、毎日。",
    "難しいことを、まず先に。",
    "始めるのに、完璧である必要はない。",
    "集中とは、多くの良いアイデアに「ノー」と言うこと。",
    "静かな心が、内なる力を生む。",
    "シンプルさは究極の洗練。",
    "今日できることが、すべての明日を良くする。",
    "行動は不安の特効薬。",
    "一度にひとつ、丁寧に。",
    "完璧より、前進を。",
    "急がば回れ。",
    "継続は力なり。",
    "今日という日は、二度と来ない。",
  ],
  es: [
    "Bien empezado es medio hecho.",
    "El secreto de avanzar es empezar.",
    "Pequeños pasos cada día.",
    "Haz primero lo difícil.",
    "No tienes que ser grande para empezar.",
    "Enfocarse es decir no a mil buenas ideas.",
    "Una mente en calma da fuerza interior.",
    "La simplicidad es la máxima sofisticación.",
    "Lo que haces hoy mejora todos tus mañanas.",
    "La acción es el antídoto de la ansiedad.",
    "Una cosa a la vez, bien hecha.",
    "Progreso, no perfección.",
    "Despacio que tengo prisa.",
    "La constancia vence lo que la dicha no alcanza.",
    "Hoy es un buen día para empezar.",
  ],
};
